force-app/main/default/objects/Arc__c/Arc__c.object-meta.xml
<CustomObject>
    <description>Arcs gathered from across the platform</description>
    <label>Arc</label>
    <nameField>
        <displayFormat>Arc-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Arc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Arcs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Arc__c/fields/Acting_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Acting_User_Id__c</fullName>
    <label>Acting User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Build_CPU_Time__c.field-meta.xml
<CustomField>
    <fullName>Build_CPU_Time__c</fullName>
    <description
  >Time is pulled from the Limits class when constructing the Log object and again when queueing. This is the delta between those two moments. Rounded down to the nearest millisecond.</description>
    <inlineHelpText>How quickly the Log object was constructed</inlineHelpText>
    <label>Build CPU Time (MS)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Build_Query_Usage__c.field-meta.xml
<CustomField>
    <fullName>Build_Query_Usage__c</fullName>
    <description
  >Query count is pulled from the Limits class when constructing the Log object and again when queueing. This is the delta between those two.</description>
    <inlineHelpText
  >Number of SOQL queries used to build the Log object</inlineHelpText>
    <label>Build Query Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <label>Exception Cause</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Exception_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Exception_Line_Number__c</fullName>
    <label>Exception Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Exception_Stack__c.field-meta.xml
<CustomField>
    <fullName>Exception_Stack__c</fullName>
    <label>Exception Stack</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Log_Number__c.field-meta.xml
<CustomField>
    <fullName>Log_Number__c</fullName>
    <inlineHelpText
  >Incremented for each log generated during a request to ensure orderability</inlineHelpText>
    <label>Log Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Public_IP_Address__c.field-meta.xml
<CustomField>
    <fullName>Public_IP_Address__c</fullName>
    <label>Public IP Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANONYMOUS</fullName>
            </value>
            <value>
                <fullName>AURA</fullName>
            </value>
            <value>
                <fullName>BATCH_ACS</fullName>
            </value>
            <value>
                <fullName>BATCH_APEX</fullName>
            </value>
            <value>
                <fullName>BATCH_CHUNK_PARALLEL</fullName>
            </value>
            <value>
                <fullName>BATCH_CHUNK_SERIAL</fullName>
            </value>
            <value>
                <fullName>BULK_API</fullName>
            </value>
            <value>
                <fullName>COMMERCE_INTEGRATION</fullName>
            </value>
            <value>
                <fullName>DISCOVERABLE_LOGIN</fullName>
            </value>
            <value>
                <fullName>FUNCTION_CALLBACK</fullName>
            </value>
            <value>
                <fullName>FUTURE</fullName>
            </value>
            <value>
                <fullName>INBOUND_EMAIL_SERVICE</fullName>
            </value>
            <value>
                <fullName>INVOCABLE_ACTION</fullName>
            </value>
            <value>
                <fullName>IOT</fullName>
            </value>
            <value>
                <fullName>QUEUEABLE</fullName>
            </value>
            <value>
                <fullName>QUICK_ACTION</fullName>
            </value>
            <value>
                <fullName>REMOTE_ACTION</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>RUNTEST_ASYNC</fullName>
            </value>
            <value>
                <fullName>RUNTEST_DEPLOY</fullName>
            </value>
            <value>
                <fullName>RUNTEST_SYNC</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
            <value>
                <fullName>SYNCHRONOUS</fullName>
            </value>
            <value>
                <fullName>TRANSACTION_FINALIZER_QUEUEABLE</fullName>
            </value>
            <value>
                <fullName>VF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Record_Context__c.field-meta.xml
<CustomField>
    <fullName>Record_Context__c</fullName>
    <inlineHelpText
  >If log was generated while working with a record, identify that record here.</inlineHelpText>
    <label>Record Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <externalId>true</externalId>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Root_Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Root_Session_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText
  >Record Id from AuthSession for root of the current session</inlineHelpText>
    <label>Root Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Session_Id__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Hash of Session Id for correlation</inlineHelpText>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/Transaction_Limits__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Limits__c</fullName>
    <label>Transaction Limits</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Arc__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Arc_Event__e/Arc_Event__e.object-meta.xml
<CustomObject>
    <description>Arcs published from across the system.</description>
    <label>Arcs Event</label>
    <pluralLabel>Arc Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Arc_Event__e/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Arc_EventTriggerHandler.cls
public with sharing class Arc_EventTriggerHandler {
  public static void processLogEvents() {
    List<Arc__c> arcs = new List<Arc__c>();
    for (SObject l : Trigger.new) {
      arcs.add(buildLogFromEvent((Arc_Event__e) l));
    }
    insert arcs;
  }

  private static Arc__c buildLogFromEvent(Arc_Event__e a) {
    Arc__c arc = new Arc__c();
    Arc.ArcWrapper w = (Arc.ArcWrapper) JSON.deserialize(
      a.Payload__c,
      Arc.ArcWrapper.class
    );
    arc.User_Id__c = w.currentUserId;
    arc.Acting_User_Id__c = w.drivingUserId;
    arc.Build_CPU_Time__c = Double.valueOf(w.eventBuildCPUTime);
    arc.Build_Query_Usage__c = Double.valueOf(w.eventBuildSOQLQueries);
    arc.Class_Name__c = w.className;
    arc.Method_Name__c = w.methodName;
    arc.Line_Number__c = Double.valueOf(w.lineNum);
    arc.Quiddity__c = w.quiddity;
    arc.Request_Id__c = w.requestId;
    arc.Timestamp__c = Datetime.newInstance(w.timestamp);
    arc.Log_Number__c = w.logNumber;
    arc.Transaction_Limits__c = JSON.serialize(w.transactionLimits);
    arc.Exception_Type__c = w.exceptionType;
    arc.Exception_Message__c = w.exceptionMessage;
    arc.Exception_Cause__c = w.exceptionCause;
    arc.Exception_Line_Number__c = w.exceptionLineNumber;
    arc.Exception_Stack__c = w.exceptionStack;
    arc.Message__c = w.message;
    arc.Details__c = w.details;
    arc.Record_Context__c = w.recordContext;
    arc.Log_Level__c = w.logLevel;
    arc.Stack_Trace__c = w.stackTrace;
    arc.Session_Id__c = w.sessionId;
    arc.Root_Session_Id__c = w.rootSessionId;
    arc.Public_IP_Address__c = w.publicIpAddress;
    return arc;
  }
}